import { useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Mantine
import { useForm } from '@mantine/form';
import { Group, TextInput, NumberInput, Button } from '@mantine/core';

// Own
import Delivery from '../components/Delivery'
import { setMaxIdleHTTPParsers } from 'http';

export type CreateDeliveryProps = {
  setIdHandler: React.Dispatch<React.SetStateAction<number>>;
}

function CreateDelivery({ setIdHandler }: CreateDeliveryProps) {
  const form = useForm({
    initialValues: {
      budget: 0,
      notes: '',
    },
    validate: {
      budget: (value) => (value < 0 ? 'Invalid budget (cannot be negative)' : null),
    },  
  });

  const handleSubmit = async (values: Object) => {
    console.log(values);
    // Get os.env BACKEND_URL or default to localhost:8000
    const backend_url = process.env.BACKEND_URL || 'http://localhost:8000';
    const response = await fetch(`${backend_url}/deliveries/create`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        type: "CREATE_DELIVERY",
        values
      }),
    });
    const {id} = await response.json();
    setIdHandler(id);
  };

  return <div className={styles.card}>
    <h2>Create Delivery &rarr;</h2>
    <form onSubmit={form.onSubmit((values) => handleSubmit(values))}>
      <NumberInput 
        label="Budget"
        {...form.getInputProps('budget')}
      />
      <TextInput 
        label="Notes"
        {...form.getInputProps('notes')}
      />
      <Group position="right" mt="md">
        <Button type="submit">Submit</Button>
      </Group>
    </form>
  </div>
}
  


export default function Home() {
  const [id, setId] = useState(0);

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Event-driven Delivery
        </h1>

        <p className={styles.description}>
          with <a href="https://nextjs.org">Next.js</a>, FastAPI, and Redis
        </p>

        <div className={styles.grid}>
          {id === 0 ? <CreateDelivery setIdHandler={setId}/> : <Delivery/> }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
